"""ensure_cosmic_conditions_table

Revision ID: 3a1384306d6e
Revises: f8710bff5b84
Create Date: 2026-01-29 03:19:23.495007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a1384306d6e"
down_revision: Union[str, None] = "f8710bff5b84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    # op.drop_table('token_blacklist')
    op.alter_column(
        "journal_entries",
        "source",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'user'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "journal_entries",
        "source",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'user'::character varying"),
    )
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("token_blacklist_pkey")),
    )
    op.create_index(op.f("ix_token_blacklist_token"), "token_blacklist", ["token"], unique=True)
    # ### end Alembic commands ###
