"""add_progression_system

Revision ID: 4387b64bc0cd
Revises: d8f7cc9e0376
Create Date: 2026-01-26 20:09:12.149849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4387b64bc0cd'
down_revision: Union[str, None] = 'd8f7cc9e0376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience_points', sa.Integer(), nullable=False),
    sa.Column('sync_rate', sa.Float(), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('sync_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_user_id'), 'player_stats', ['user_id'], unique=True)
    op.add_column('quests', sa.Column('category', sa.String(), nullable=False))
    op.add_column('quests', sa.Column('xp_reward', sa.Integer(), nullable=False))
    op.add_column('quests', sa.Column('insight_id', sa.Integer(), nullable=True))
    op.alter_column('quests', 'difficulty',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'quests', 'reflection_prompts', ['insight_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.alter_column('quests', 'difficulty',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('quests', 'insight_id')
    op.drop_column('quests', 'xp_reward')
    op.drop_column('quests', 'category')
    op.drop_index(op.f('ix_player_stats_user_id'), table_name='player_stats')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
