"""add_insight_and_quest_tables

Revision ID: d8f7cc9e0376
Revises: 4bac7cdfa197
Create Date: 2026-01-26 19:51:16.989891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = "d8f7cc9e0376"
down_revision: Union[str, None] = "4bac7cdfa197"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("recurrence", sa.String(), nullable=False),
        sa.Column("cron_expression", sa.String(), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("tags", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quests_user_id"), "quests", ["user_id"], unique=False)
    op.create_table(
        "reflection_prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("trigger_context", sa.JSON(), nullable=True),
        sa.Column("event_phase", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reflection_prompts_status"), "reflection_prompts", ["status"], unique=False)
    op.create_index(op.f("ix_reflection_prompts_topic"), "reflection_prompts", ["topic"], unique=False)
    op.create_index(op.f("ix_reflection_prompts_user_id"), "reflection_prompts", ["user_id"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mood_score", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("prompt_id", sa.Integer(), nullable=True),
        sa.Column("context_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["reflection_prompts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_journal_entries_user_id"), "journal_entries", ["user_id"], unique=False)
    op.create_table(
        "quest_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quest_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["quests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quest_logs_quest_id"), "quest_logs", ["quest_id"], unique=False)
    op.drop_index(op.f("ix_token_blacklist_token"), table_name="token_blacklist")
    op.drop_table("token_blacklist")
    op.alter_column(
        "chat_messages",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "chat_messages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("chat_messages_session_id_idx"), table_name="chat_messages")
    op.create_index(op.f("ix_chat_messages_session_id"), "chat_messages", ["session_id"], unique=False)
    op.alter_column(
        "chat_sessions",
        "contribute_to_memory",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "chat_sessions",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "chat_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("chat_sessions_type_idx"), table_name="chat_sessions")
    op.drop_index(op.f("chat_sessions_user_id_idx"), table_name="chat_sessions")
    op.create_index(op.f("ix_chat_sessions_session_type"), "chat_sessions", ["session_type"], unique=False)
    op.create_index(op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False)
    op.alter_column(
        "embeddings", "embedding", existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
    )
    op.drop_index(
        op.f("embeddings_embedding_idx"),
        table_name="embeddings",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.create_unique_constraint(None, "post", ["id"])
    op.create_unique_constraint(None, "rate_limit", ["id"])
    op.create_unique_constraint(None, "tier", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tier", type_="unique")
    op.drop_constraint(None, "rate_limit", type_="unique")
    op.drop_constraint(None, "post", type_="unique")
    op.create_index(
        op.f("embeddings_embedding_idx"),
        "embeddings",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.alter_column("embeddings", "embedding", existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True)
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_session_type"), table_name="chat_sessions")
    op.create_index(op.f("chat_sessions_user_id_idx"), "chat_sessions", ["user_id"], unique=False)
    op.create_index(op.f("chat_sessions_type_idx"), "chat_sessions", ["session_type"], unique=False)
    op.alter_column(
        "chat_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_sessions",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "chat_sessions",
        "contribute_to_memory",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.create_index(op.f("chat_messages_session_id_idx"), "chat_messages", ["session_id"], unique=False)
    op.alter_column(
        "chat_messages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_messages",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("token_blacklist_pkey")),
    )
    op.create_index(op.f("ix_token_blacklist_token"), "token_blacklist", ["token"], unique=True)
    op.drop_index(op.f("ix_quest_logs_quest_id"), table_name="quest_logs")
    op.drop_table("quest_logs")
    op.drop_index(op.f("ix_journal_entries_user_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_reflection_prompts_user_id"), table_name="reflection_prompts")
    op.drop_index(op.f("ix_reflection_prompts_topic"), table_name="reflection_prompts")
    op.drop_index(op.f("ix_reflection_prompts_status"), table_name="reflection_prompts")
    op.drop_table("reflection_prompts")
    op.drop_index(op.f("ix_quests_user_id"), table_name="quests")
    op.drop_table("quests")
    # ### end Alembic commands ###
