"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                    COUNCIL JOURNAL GENERATOR                                 ║
║                                                                              ║
║   Automatically generates high-fidelity journal entries for cosmic events.  ║
║   Synthesizes I-Ching, Cardology, and Council data into reflective content. ║
║                                                                              ║
║   Author: GUTTERS Project                                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

from datetime import UTC, datetime
from enum import Enum
from typing import Any, Dict, Optional

import structlog
from pydantic import BaseModel, Field

from src.app.modules.intelligence.council.service import (
    CouncilService,
    CouncilSynthesisResult,
    GateTransition,
    HexagramState,
    get_council_service,
)
from src.app.modules.intelligence.iching import GATE_DATABASE

logger = structlog.get_logger(__name__)


class CosmicEventType(str, Enum):
    """Types of cosmic events that trigger journal entries."""
    GATE_TRANSITION = "gate_transition"
    LINE_SHIFT = "line_shift"
    RESONANCE_SHIFT = "resonance_shift"
    DAILY_SYNTHESIS = "daily_synthesis"
    SIGNIFICANT_ALIGNMENT = "significant_alignment"


class GeneratedJournalEntry(BaseModel):
    """A generated journal entry for cosmic events."""
    title: str
    content: str
    event_type: CosmicEventType
    cosmic_context: Dict[str, Any]
    reflection_prompts: list[str]
    tags: list[str]
    mood_suggestions: list[str] = []
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class CouncilJournalGenerator:
    """
    Generates sophisticated journal entries for Council of Systems events.

    Creates reflective, insightful content that synthesizes:
    - I-Ching gate/line transitions
    - Gene Key frequency spectrum
    - Cardology period context
    - Cross-system resonance
    """

    def __init__(self, council_service: CouncilService = None):
        """Initialize with optional council service."""
        self._council = council_service or get_council_service()

    # =========================================================================
    # GATE TRANSITION ENTRIES
    # =========================================================================

    def generate_gate_transition_entry(
        self,
        transition: GateTransition,
        synthesis: CouncilSynthesisResult = None
    ) -> GeneratedJournalEntry:
        """
        Generate a journal entry for a gate transition.

        Args:
            transition: Gate transition data
            synthesis: Optional current synthesis

        Returns:
            GeneratedJournalEntry with full cosmic context
        """
        new_gate = transition.new_gate_data or {}
        old_gate = transition.old_gate_data or {}

        # Build title
        gate_name = new_gate.get("hd_name", f"Gate {transition.new_sun_gate}")
        title = f"🌀 Gate Shift: Entering {gate_name}"

        # Build content
        old_name = old_gate.get("hd_name", f"Gate {transition.old_sun_gate}")
        new_gift = new_gate.get("gene_key_gift", "Unknown")
        new_shadow = new_gate.get("gene_key_shadow", "Unknown")
        new_siddhi = new_gate.get("gene_key_siddhi", "Unknown")
        old_gift = old_gate.get("gene_key_gift", "Unknown")

        content = f"""## Cosmic Transit: {old_name} → {gate_name}

The Sun has moved from **Gate {transition.old_sun_gate}** ({old_name}) into
**Gate {transition.new_sun_gate}** ({gate_name}).

### Gene Key Frequency Spectrum

- **Shadow**: {new_shadow} — The unconscious pattern to observe
- **Gift**: {new_gift} — The frequency to cultivate
- **Siddhi**: {new_siddhi} — The highest expression

### Polarity

Earth rests in Gate {transition.new_earth_gate}, creating a polarity axis that invites integration.

### Integration Notes

The transition from {old_gift} to {new_gift} marks a shift in the collective
and personal field. This is an invitation to:

1. **Release** attachment to the previous gate's themes
2. **Welcome** the new frequency with curiosity
3. **Observe** how this transition manifests in your inner and outer world

---

*This entry was automatically generated by the Council of Systems to mark a significant cosmic transit.*
"""

        # Reflection prompts
        prompts = [
            f"How have I been embodying {old_gift} in the last few days?",
            f"What does {new_gift} mean to me personally?",
            f"Where in my life might {new_shadow} be operating unconsciously?",
            "What synchronicities or patterns have I noticed during this transition?",
        ]

        # Tags
        tags = [
            "cosmic-transit",
            f"gate-{transition.new_sun_gate}",
            "i-ching",
            "gene-keys",
            new_gift.lower().replace(" ", "-") if new_gift else "unknown",
        ]

        # Mood suggestions based on gate
        mood_suggestions = self._get_mood_suggestions_for_gate(transition.new_sun_gate)

        return GeneratedJournalEntry(
            title=title,
            content=content,
            event_type=CosmicEventType.GATE_TRANSITION,
            cosmic_context={
                "old_gate": transition.old_sun_gate,
                "new_gate": transition.new_sun_gate,
                "line": transition.new_line,
                "gate_data": new_gate,
            },
            reflection_prompts=prompts,
            tags=tags,
            mood_suggestions=mood_suggestions,
            timestamp=transition.timestamp,
        )

    # =========================================================================
    # DAILY SYNTHESIS ENTRIES
    # =========================================================================

    def generate_daily_synthesis_entry(
        self,
        synthesis: CouncilSynthesisResult,
        hexagram: HexagramState
    ) -> GeneratedJournalEntry:
        """
        Generate a daily cosmic weather journal entry.

        Args:
            synthesis: Council synthesis result
            hexagram: Current hexagram state

        Returns:
            GeneratedJournalEntry with daily cosmic weather
        """
        # Title
        title = f"☀️ Daily Code: Gate {hexagram.sun_gate}.{hexagram.sun_line} — {hexagram.sun_gene_key_gift}"

        # Resonance emoji
        resonance_emoji = {
            "harmonic": "✨",
            "supportive": "🌿",
            "neutral": "⚖️",
            "challenging": "🔥",
            "dissonant": "🌊",
        }.get(synthesis.resonance_type, "⭐")

        content = f"""## Council of Systems Daily Synthesis

### I-Ching Hexagram (Micro-Cycle)

**Sun Position**: Gate {hexagram.sun_gate}.{hexagram.sun_line} — {hexagram.sun_gate_name}
**Earth Position**: Gate {hexagram.earth_gate}.{hexagram.earth_line} — {hexagram.earth_gate_name}

**Polarity Theme**: {hexagram.polarity_theme}

**Gene Key Gift**: {hexagram.sun_gene_key_gift}
**Gene Key Shadow**: {hexagram.sun_gene_key_shadow}

### Cardology Context (Macro-Cycle)

**Current Symbol**: {synthesis.macro_symbol}
**Archetype**: {synthesis.macro_archetype}
**Keynote**: {synthesis.macro_keynote}

### Cross-System Resonance {resonance_emoji}

**Resonance**: {synthesis.resonance_type.title()} ({synthesis.resonance_score:.0%})

{synthesis.resonance_description}

### Today's Unified Frequency

- **Shadow to Observe**: {synthesis.unified_shadow}
- **Gift to Cultivate**: {synthesis.unified_gift}
- **Siddhi Potential**: {synthesis.unified_siddhi}

---

*Synthesized by the Council of Systems*
"""

        prompts = [
            f"How does {hexagram.sun_gene_key_gift} show up in my life today?",
            f"What aspect of {synthesis.macro_keynote} resonates with my current experience?",
            f"How can I integrate the {hexagram.polarity_theme} polarity?",
            f"What would it look like to embody the {synthesis.resonance_type} resonance today?",
        ]

        tags = [
            "daily-synthesis",
            "council-of-systems",
            f"gate-{hexagram.sun_gate}",
            synthesis.resonance_type,
            hexagram.sun_gene_key_gift.lower().replace(" ", "-"),
        ]

        return GeneratedJournalEntry(
            title=title,
            content=content,
            event_type=CosmicEventType.DAILY_SYNTHESIS,
            cosmic_context={
                "hexagram": {
                    "sun_gate": hexagram.sun_gate,
                    "sun_line": hexagram.sun_line,
                    "earth_gate": hexagram.earth_gate,
                },
                "synthesis": {
                    "resonance_score": synthesis.resonance_score,
                    "resonance_type": synthesis.resonance_type,
                },
            },
            reflection_prompts=prompts,
            tags=tags,
            timestamp=synthesis.timestamp,
        )

    # =========================================================================
    # RESONANCE SHIFT ENTRIES
    # =========================================================================

    def generate_resonance_shift_entry(
        self,
        old_resonance: str,
        new_resonance: str,
        synthesis: CouncilSynthesisResult
    ) -> GeneratedJournalEntry:
        """
        Generate a journal entry for resonance shift.

        Args:
            old_resonance: Previous resonance type
            new_resonance: New resonance type
            synthesis: Current synthesis

        Returns:
            GeneratedJournalEntry documenting the shift
        """
        # Direction arrow
        direction = self._get_resonance_direction(old_resonance, new_resonance)

        title = f"⚡ Resonance Shift: {old_resonance.title()} {direction} {new_resonance.title()}"

        content = f"""## Cross-System Resonance Shift

The harmonic relationship between the Council of Systems has shifted.

**Previous State**: {old_resonance.title()}
**Current State**: {new_resonance.title()}
**New Resonance Score**: {synthesis.resonance_score:.0%}

### What This Means

{self._get_resonance_meaning(old_resonance, new_resonance)}

### Current Elemental Profile

{self._format_element_profile(synthesis.element_profile)}

### Integration Guidance

{synthesis.resonance_description}

---

*Resonance shifts mark significant moments in the cosmic weather. Use this
awareness to navigate your day with intention.*
"""

        prompts = [
            f"How did the {old_resonance} energy feel in my body and mind?",
            f"What does the shift to {new_resonance} invite me to explore?",
            "What action can I take to honor this energetic transition?",
        ]

        tags = [
            "resonance-shift",
            old_resonance,
            new_resonance,
            "council-of-systems",
        ]

        return GeneratedJournalEntry(
            title=title,
            content=content,
            event_type=CosmicEventType.RESONANCE_SHIFT,
            cosmic_context={
                "old_resonance": old_resonance,
                "new_resonance": new_resonance,
                "resonance_score": synthesis.resonance_score,
            },
            reflection_prompts=prompts,
            tags=tags,
        )

    # =========================================================================
    # HELPER METHODS
    # =========================================================================

    def _get_mood_suggestions_for_gate(self, gate: int) -> list[str]:
        """Get mood/feeling suggestions based on gate themes."""
        gate_data = GATE_DATABASE.get(gate)
        if not gate_data:
            return []

        # Map centers to moods
        center_moods = {
            "Head": ["inspired", "curious", "contemplative"],
            "Ajna": ["analytical", "focused", "questioning"],
            "Throat": ["expressive", "communicative", "creative"],
            "G": ["centered", "purposeful", "authentic"],
            "Heart": ["willful", "determined", "courageous"],
            "Spleen": ["intuitive", "alert", "instinctual"],
            "Sacral": ["vital", "responsive", "generative"],
            "Solar Plexus": ["emotional", "sensitive", "passionate"],
            "Root": ["pressured", "driven", "grounded"],
        }

        center = gate_data.hd_center if gate_data else "G"
        return center_moods.get(center, ["reflective", "aware"])

    def _get_resonance_direction(self, old: str, new: str) -> str:
        """Get arrow direction for resonance change."""
        order = ["dissonant", "challenging", "neutral", "supportive", "harmonic"]
        try:
            old_idx = order.index(old)
            new_idx = order.index(new)
            return "→" if new_idx > old_idx else "←"
        except ValueError:
            return "→"

    def _get_resonance_meaning(self, old: str, new: str) -> str:
        """Get explanation for resonance transition."""
        meanings = {
            ("challenging", "harmonic"): (
                "A significant shift from tension to flow. The systems that were in "
                "opposition are now working together."
            ),
            ("harmonic", "challenging"): (
                "Moving into a period of productive tension. This is not negative—"
                "it's an invitation for deeper integration."
            ),
            ("neutral", "harmonic"): (
                "The neutral potential has crystallized into alignment. A favorable "
                "time for aligned action."
            ),
            ("neutral", "challenging"): (
                "The open field has developed friction. Use this energy for "
                "transformation."
            ),
        }
        return meanings.get(
            (old, new),
            f"The shift from {old} to {new} marks a new chapter in the cosmic narrative."
        )

    def _format_element_profile(self, profile: Dict[str, str]) -> str:
        """Format element profile as markdown."""
        element_emojis = {
            "fire": "🔥",
            "water": "💧",
            "air": "💨",
            "earth": "🌍",
            "ether": "✨",
        }
        lines = []
        for system, element in profile.items():
            emoji = element_emojis.get(element.lower(), "⭐")
            lines.append(f"- **{system}**: {emoji} {element.title()}")
        return "\n".join(lines)


# =============================================================================
# SINGLETON
# =============================================================================

_journal_generator: Optional[CouncilJournalGenerator] = None


def get_journal_generator() -> CouncilJournalGenerator:
    """Get or create the journal generator singleton."""
    global _journal_generator
    if _journal_generator is None:
        _journal_generator = CouncilJournalGenerator()
    return _journal_generator
